name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    name: WordPress Coding Standards

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml
        coverage: none

    - name: Cache Composer packages
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-8.2-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-8.2-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHPCS
      run: composer lint

  assets:
    runs-on: ubuntu-latest
    name: Build Frontend Assets

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: "24"
        cache: "npm"

    - name: Install dependencies
      run: npm ci

    - name: Build frontend assets
      run: npm run build
